// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ_oGVhcLdZ7x1FUyU_LRFNQENuBRgTro',
    appId: '1:777988038385:web:fdd89890890a1555999350',
    messagingSenderId: '777988038385',
    projectId: 'shemesh-test',
    authDomain: 'shemesh-test.firebaseapp.com',
    storageBucket: 'shemesh-test.firebasestorage.app',
    measurementId: 'G-B6CN10MZH9',
  );

}
